# Generated by Django 4.2.5 on 2024-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_peertube_runner_connector",
            "0003_runnerjob_domain_alter_runnerjob_error",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="language",
            field=models.CharField(
                blank=True, help_text="Language of the video", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="transcriptFileName",
            field=models.CharField(
                blank=True,
                help_text="Transcript filename on the storage",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="videojobinfo",
            name="pendingTranscript",
            field=models.IntegerField(
                default=0, help_text="Counter of pending transcript operations"
            ),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="type",
            field=models.CharField(
                choices=[
                    ("vod-web-video-transcoding", "Vod Web Video Transcoding"),
                    ("vod-hls-transcoding", "Vod Hls Transcoding"),
                    ("vod-audio-merge-transcoding", "Vod Audio Merge Transcoding"),
                    ("live-rtmp-hls-transcoding", "Live Rtmp Hls Transcoding"),
                    ("video-studio-transcoding", "Video Studio Transcoding"),
                    ("video-transcription", "Video Transcription"),
                ],
                help_text="Job type",
                max_length=255,
            ),
        ),
    ]
